# Generated by Django 5.1.4 on 2025-03-26 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashierprofile",
            name="cashier_branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Authentication.branch",
            ),
        ),
    ]
