# Generated by Django 5.1.4 on 2025-03-27 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Authentication", "0002_alter_cashierprofile_cashier_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="barcode_image",
            field=models.ImageField(blank=True, null=True, upload_to="barcodes/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="barcode",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_code",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
