# Generated by Django 5.1.4 on 2025-03-27 00:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Authentication", "0003_product_barcode_image_alter_product_barcode_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="Branch",
            new_name="branch",
        ),
    ]
