# Generated by Django 5.1.4 on 2025-03-28 06:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Authentication", "0004_rename_branch_product_branch"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "transfer_type",
                    models.CharField(
                        choices=[
                            ("INTERNAL", "Between Branches"),
                            ("SUPPLIER", "From Supplier"),
                            ("CUSTOMER", "To Customer"),
                            ("ADJUSTMENT", "Inventory Adjustment"),
                        ],
                        default="INTERNAL",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("COMPLETED", "Completed"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_transfers",
                        to="Authentication.cashierprofile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_transfers",
                        to="Authentication.cashierprofile",
                    ),
                ),
                (
                    "from_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_transfers",
                        to="Authentication.branch",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers",
                        to="Authentication.product",
                    ),
                ),
                (
                    "to_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_transfers",
                        to="Authentication.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Transfer",
                "verbose_name_plural": "Product Transfers",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["reference"], name="Authenticat_referen_51b5af_idx"
                    ),
                    models.Index(
                        fields=["status"], name="Authenticat_status_e92887_idx"
                    ),
                    models.Index(
                        fields=["product"], name="Authenticat_product_182779_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="Authenticat_created_2fd630_idx"
                    ),
                ],
            },
        ),
    ]
