# Generated by Django 5.1.4 on 2025-03-28 07:34

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Authentication", "0005_producttransfer"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashierprofile",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location="/media/profile_pics/"
                ),
                upload_to="profile_pics/",
            ),
        ),
    ]
